CREATE VIEW ConfigService_Viajes AS SELECT
  DbViaje_0.ID,
  DbViaje_0.vehiculo_ID,
  DbViaje_0.chofer_ID,
  DbViaje_0.ruta_ID,
  DbViaje_0.fecha,
  DbViaje_0.horaSalida,
  DbViaje_0.horaLlegada,
  DbViaje_0.horaLlegadaReal,
  DbViaje_0.kilometrosRecorridos,
  DbViaje_0.minHoraSalida,
  DbViaje_0.litrosSalida,
  DbViaje_0.pesoCarga,
  DbViaje_0.consumoRealTotal,
  DbViaje_0.consumoTeoricoTotal,
  DbViaje_0.kilometrosPorLitro,
  DbViaje_0.horasPorLitro,
  DbViaje_0.estatus,
  DbViaje_0.proveedor_ID,
  DbViaje_0.rendimientoTeorico,
  DbViaje_0.combustibleTeorico,
  DbViaje_0.costoTeorico,
  DbViaje_0.rubro_ID,
  DbViaje_0.pesoIda,
  DbViaje_0.pesoVuelta,
  ruta_3.destino AS nombreRuta,
  ruta_3.origen AS origenRuta,
  ruta_3.latitudOrigen AS origenLatitud,
  ruta_3.longitudOrigen AS origenLongitud,
  DbViaje_0.origen,
  DbViaje_0.latitudOrigen,
  DbViaje_0.longitudOrigen,
  DbViaje_0.destino,
  DbViaje_0.latitudDestino,
  DbViaje_0.longitudDestino,
  chofer_2.nombre || ' ' || chofer_2.apellido AS choferNombreCompleto,
  vehiculo_1.placa AS vehiculoPlaca,
  vehiculo_1.modelo AS vehiculoModelo,
  ruta_3.distanciaKm AS distanciaRuta,
  ruta_3.distanciaKm AS distanciaTotalKm,
  ruta_3.latitud AS rutaLatitud,
  ruta_3.longitud AS rutaLongitud,
  0 AS viajesEnRuta,
  0 AS viajesVehiculoEnRuta,
  0 AS consumoUltimo1,
  0 AS consumoUltimo2,
  0 AS consumoUltimo3,
  0 AS consumoPromedioRuta,
  0 AS consumoUltimoViajeRuta,
  vehiculo_1.capacidadTotal AS vehiculoCapacidadTotal,
  vehiculo_1.rendimientoBase AS vehiculoRendimientoBase,
  chofer_2.cedula AS choferCedula,
  chofer_2.telefono AS choferTelefono,
  chofer_2.choferImage AS choferImagen,
  DbViaje_0.numeroViaje,
  DbViaje_0.numeroViajeFormateado
FROM (((gas_app_Viaje AS DbViaje_0 LEFT JOIN gas_app_Vehiculo AS vehiculo_1 ON DbViaje_0.vehiculo_ID = vehiculo_1.ID) LEFT JOIN gas_app_Chofer AS chofer_2 ON DbViaje_0.chofer_ID = chofer_2.ID) LEFT JOIN gas_app_Ruta AS ruta_3 ON DbViaje_0.ruta_ID = ruta_3.ID);

